import type { Metadata } from "next";
import TestComponent from "@/components/TestComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <TestComponent from={"Layout"} />
        {children}
      </body>
    </html>
  );
}
